set nocompatible
syntax on

filetype off
filetype plugin indent on

set hlsearch
set showmatch
set incsearch
set showcmd

set background=dark

function FakeTabs4()
    set tabstop=4 shiftwidth=4 softtabstop=4 expandtab
endfunction

function FakeTabs2()
    set tabstop=2 shiftwidth=2 softtabstop=2 expandtab
endfunction

function RealTabs()
    set tabstop=8 shiftwidth=8 softtabstop=8 noexpandtab
endfunction

call FakeTabs4()

map <F2> <ESC>:call FakeTabs2()<CR>:echo "Fake tabs 2"<CR>
map <F4> <ESC>:call FakeTabs4()<CR>:echo "Fake tabs 4"<CR>
map <F8> <ESC>:call RealTabs()<CR>:echo "Real tabs"<CR>
map <F9> <ESC>:set background=dark<CR>:echo "Set to dark background"<CR>
map <F10> <ESC>:set background=light<CR>:echo "Set to light background"<CR>

" CCT files - Character Conversation Trees
au BufNewFile,BufRead *.cct set filetype=javascript
au FileType javascript :call FakeTabs2()

